config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :site_users

  resources :suppliers

  resources :trainings

  resources :clients

  resources :supplies

  resources :roles

  resources :areas

  resources :users

  get '/signup'  => 'site_users#new'
  post '/site_users' => 'site_users#create' 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

   root 'rh_menu#index'

end

app/models/training.rb
class Training < ActiveRecord::Base
	has_many :users
	validates :expositor, presence: true
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:course_name, :topic, :expositor, :start_date, :duration, :attendance_id)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= simple_form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :course_name, placeholder: 'Enter Course Name' %><br>    
  </div>
  <div class="field">
    <%= f.input :topic, placeholder: 'Enter Topic' %><br>
  </div>
  <div class="field">
    <%= f.association :users, label_method: :name %><br>
  </div>
  <div class="field">
    <%= f.input :start_date %><br>
  </div>
  <div class="field">
    <%= f.input :duration %><br>
  </div>
  <div class="field">
    <%= f.input :attendance_id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainings</h1>

<table>
  <thead>
    <tr>
      <th>Course name</th>
      <th>Topic</th>
      <th>Expositor</th>
      <th>Start date</th>
      <th>Duration</th>
      <th>Attendance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.course_name %></td>
        <td><%= training.topic %></td>
        <td><%= training.expositor %></td>
        <td><%= training.start_date %></td>
        <td><%= training.duration %></td>
        <td><%= training.attendance_id %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @training.course_name %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @training.topic %>
</p>

<p>
  <strong>Expositor:</strong>
  <%= @training.expositor %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @training.start_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @training.duration %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @training.attendance_id %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>