config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :site_users

  resources :suppliers

  resources :trainings

  resources :clients

  resources :supplies

  resources :roles

  resources :areas

  resources :users

  get '/signup'  => 'site_users#new'
  post '/site_users' => 'site_users#create' 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

   root 'rh_menu#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :logins
	belongs_to :area
	belongs_to :role
	belongs_to :training, :class_name => 'Training', :foreign_key => 'expositor'
	belongs_to :login, :class_name => 'Login', :foreign_key => 'name'
	validates :area, :role, presence: true
end
	

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :birthdate, :age, :phone, :emergency_number, :curp, :imms, :rfc, :employee_id, :date_of_admission, :area_id, :boss, :salary, :role_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-inline' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.input :name %>
    </div>
    <div class="field">
      <%= f.input :birthdate, :start_year=>1900 %>
    </div>
    <div class="field">
      <%= f.input :age %>
    </div>
    <div class="field">
      <%= f.input :phone %>
    </div>
    <div class="field">
      <%= f.input :emergency_number %>
    </div>
    <div class="field">
      <%= f.input :curp %>
    </div>
    <div class="field">
      <%= f.input :imms %>
    </div>
    <div class="field">
      <%= f.input :rfc %>
    </div>
    <div class="field">
      <%= f.input :employee_id %>
    </div>
    <div class="field">
      <%= f.input :date_of_admission %>
    </div>
    <div class="field">
      <%= f.association :area, label_method: :area_name %>
    </div>
    <div class="field">
      <%= f.association :area, label_method: :area_manager %>
    </div>
    <div class="field">
      <%= f.input :salary %>
    </div>
    <div class="field">
      <%= f.association :role, label_method: :role %>
    </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Usuarios</h1>
<div class="table-striped">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Fecha de Nacimiento</th>
        <th>Edad</th>
        <th>Telefono</th>
        <th>Número de Emergencia</th>
        <th>CURP</th>
        <th>IMSS</th>
        <th>RFC</th>
        <th>ID</th>
        <th>Fecha de Admisión</th>
        <th>Area</th>
        <th>Jefe</th>
        <th>Salario</th>
        <th>Posición</th>
        <th colspan="3"></th>
      </tr>
    </thead>
</div>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.age %></td>
        <td><%= user.phone %></td>
        <td><%= user.emergency_number %></td>
        <td><%= user.curp %></td>
        <td><%= user.imms %></td>
        <td><%= user.rfc %></td>
        <td><%= user.employee_id %></td>
        <td><%= user.date_of_admission %></td>
        <td><%= user.area.area_name %></td>
        <td><%= user.boss %></td>
        <td><%= user.salary %></td>
        <td><%= user.role.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Area', new_area_path, remote: true %>
<%= link_to 'New Role', new_role_path, remote: true %>
<%= link_to 'New User', new_user_path, remote: true %> 

<div id="user-modal">
  <div id="inner-user-modal"></div>
</div>

<div id="area-modal">
  <div id="inner-area-modal"></div>
</div>

<div id="role-modal">
  <div id="inner-role-modal"></div>
</div>


<br>

      

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.haml
$("#inner-user-modal").html("#{escape_javascript(render 'new')}")
$("#user-modal").hide().show();

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Emergency number:</strong>
  <%= @user.emergency_number %>
</p>

<p>
  <strong>Curp:</strong>
  <%= @user.curp %>
</p>

<p>
  <strong>Imms:</strong>
  <%= @user.imms %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @user.rfc %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @user.employee_id %>
</p>

<p>
  <strong>Date of admission:</strong>
  <%= @user.date_of_admission %>
</p>

<p>
  <strong>Area:</strong>
  <%= @user.area.area_name %>
</p>

<p>
  <strong>Boss:</strong>
  <%= @user.boss %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @user.salary %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>