config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :site_users

  resources :suppliers

  resources :trainings

  resources :clients

  resources :supplies

  resources :roles

  resources :areas

  resources :users

  get '/signup'  => 'site_users#new'
  post '/site_users' => 'site_users#create' 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

   root 'rh_menu#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :area
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:area_id, :category, :company_name, :contact_name, :position, :email, :phone, :birthdate, :sex, :company_adress)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.number_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.check_box :sex %>
  </div>
  <div class="field">
    <%= f.label :company_adress %><br>
    <%= f.text_field :company_adress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Category</th>
      <th>Company name</th>
      <th>Contact name</th>
      <th>Position</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Birthdate</th>
      <th>Sex</th>
      <th>Company adress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.area_id %></td>
        <td><%= client.category %></td>
        <td><%= client.company_name %></td>
        <td><%= client.contact_name %></td>
        <td><%= client.position %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <td><%= client.birthdate %></td>
        <td><%= client.sex %></td>
        <td><%= client.company_adress %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @client.area_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @client.category %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @client.company_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @client.contact_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @client.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @client.birthdate %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @client.sex %>
</p>

<p>
  <strong>Company adress:</strong>
  <%= @client.company_adress %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>